CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -pedantic -g

PROG = game_play
SRC = game.c game_play.c
HDR = game.h
OBJ = $(SRC:.c=.o)

$(PROG): $(OBJ)
$(OBJ): $(HDR)
TAGS: $(SRC) $(HDR)
	etags $^
tags: $(SRC) $(HDR)
	ctags $^
.PHONY: clean
clean:
	$(RM) $(PROG) $(OBJ)
